"""F4 — resolution probe: DoH A/MX lookups + HTTP redirect-chain
classification.

DoH JSON shape verified live against Cloudflare's resolver on
2026-08-20 (Status 0 = NOERROR, Status 3 = NXDOMAIN, Answer[].data holds
the record value; MX data is "<priority> <host>."). The forwards-home
fixture (T-03) is real: gogle.com answers 301 -> https://www.google.com/
(D-05, D-06), confirmed live the same day.
"""

from __future__ import annotations

import asyncio
import re
from typing import Optional
from urllib.parse import urlparse

import httpx

from squatwatch.cache import Cache, get_semaphore
from squatwatch.models import ProbeInfo, ProbeKind

MAX_HOPS = 5
TIMEOUT_SECONDS = 4.0
PROBE_CONCURRENCY = 20

# Heuristic: nameservers commonly used by parking services (not
# exhaustive — the methodology page documents this as judgment).
_PARKING_NAMESERVER_MARKERS = (
    "sedoparking.com",
    "parkingcrew.net",
    "bodis.com",
    "above.com",
    "parklogic.com",
    "voodoo.com",
    "parked.com",
    "dsparking.com",
    "wixdns.net",  # excluded below via allowlist check if brand uses Wix legitimately
)

# B2 (project_brief.md Section 9b; Praktiker-consulted, expert_consultations.md
# 2026-08-20): a bare MX host of "localhost" is not reachable from the public
# internet and cannot actually receive mail — it is a parking service's
# default placeholder, not evidence an attacker could intercept mail the way
# F4/F6/F9 mean "mail configured." Reusing _PARKING_NAMESERVER_MARKERS: an MX
# host published inside a known parking provider's own zone is the same kind
# of non-functional default, not a distinct signal. RFC 7505 null MX ("0 .")
# is already filtered below by the empty-host check — judgment, not FACT,
# documented on the methodology page.
_MX_PLACEHOLDER_HOSTS = ("localhost",)

_PARKING_PAGE_MARKERS = (
    "this domain is for sale",
    "buy this domain",
    "domain parking",
    "related searches",
    "this webpage was generated by the domain owner",
    "this domain may be for sale",
    "inquire about this domain",
    "make an offer",
    "is parked free",
    "courtesy of",
)

# Checked only against the page title / first visible heading, never the
# full body: some of these ("parked", "parking", "sedo") are common
# enough words that a body-wide search would false-positive on an
# unrelated live-other site that merely mentions them in passing. A
# squatter-parked landing page puts one of these in the title or the
# H1 (academy-fix: naeee.com/namu.com-style "Domain Name For Sale"
# pages were falling through to live-other and picking up the
# established-unrelated line).
_PARKED_TITLE_MARKERS = (
    "for sale",
    "is for sale",
    "domain name for sale",
    "buy this domain",
    "this domain is available",
    "parked",
    "parking",
    "make an offer",
    "sedo",
    "dan.com",
    "afternic",
    "hugedomains",
    "undeveloped",
)

_TITLE_RE = re.compile(rb"<title[^>]*>(.*?)</title>", re.IGNORECASE | re.DOTALL)
_HEADING_RE = re.compile(rb"<h1[^>]*>(.*?)</h1>", re.IGNORECASE | re.DOTALL)
_INNER_TAG_RE = re.compile(rb"<[^>]+>")


def _registrable_and_www(brand_registrable: str) -> set[str]:
    return {brand_registrable, f"www.{brand_registrable}"}


def _in_parking_zone(host: str) -> bool:
    """Adversarial re-review, Round 3: a raw substring `in` check against
    `_PARKING_NAMESERVER_MARKERS` (e.g. "above.com") false-positives on a
    real business self-hosting mail at a host like "mail.riseabove.com"
    — "riseabove.com" contains "above.com" as a substring but is not in
    that zone. Only the marker itself, or a host inside it (a real DNS
    subdomain, dot-separated), counts.
    """
    return any(
        host == marker or host.endswith("." + marker)
        for marker in _PARKING_NAMESERVER_MARKERS
    )


async def _doh_lookup(
    client: httpx.AsyncClient, resolver_url: str, domain: str, record_type: str
) -> list[str]:
    try:
        resp = await client.get(
            resolver_url,
            params={"name": domain, "type": record_type},
            headers={"Accept": "application/dns-json"},
            timeout=TIMEOUT_SECONDS,
        )
    except (httpx.TimeoutException, httpx.TransportError):
        return []
    if resp.status_code != 200:
        return []
    body = resp.json()
    if body.get("Status") != 0:
        return []
    out = []
    for answer in body.get("Answer", []):
        if answer.get("type") not in (1, 2, 15):  # A, NS, MX
            continue
        data = answer.get("data", "").rstrip(".")
        if record_type == "MX":
            parts = data.split(" ", 1)
            data = parts[1] if len(parts) == 2 else data
            # RFC 7505 null MX ("0 .") explicitly declares "no mail
            # service" — after stripping the trailing dot this parses to
            # an empty host, which must NOT count as "mail configured."
            if not data.strip():
                continue
            # B2: "localhost" and hosts inside a known parking provider's
            # zone are placeholder MX values a parking service publishes
            # by default, not a functioning mail destination — same
            # non-functional bucket as null MX, not "mail configured."
            host = data.strip().lower()
            if host in _MX_PLACEHOLDER_HOSTS or _in_parking_zone(host):
                continue
        out.append(data)
    return out


def _extract_title(body: bytes) -> Optional[str]:
    match = _TITLE_RE.search(body)
    if not match:
        return None
    title = match.group(1).decode("utf-8", errors="replace").strip()
    return title[:200] if title else None


def _extract_first_heading(body: bytes) -> Optional[str]:
    match = _HEADING_RE.search(body)
    if not match:
        return None
    inner = _INNER_TAG_RE.sub(b"", match.group(1))
    heading = inner.decode("utf-8", errors="replace").strip()
    return heading[:200] if heading else None


async def _follow_chain(
    client: httpx.AsyncClient, domain: str
) -> tuple[list[str], Optional[str], Optional[bytes], Optional[int]]:
    """Returns (chain_urls, final_host, final_body, final_status)."""
    url = f"http://{domain}/"
    chain: list[str] = []
    for _hop in range(MAX_HOPS):
        try:
            resp = await client.get(
                url, timeout=TIMEOUT_SECONDS, follow_redirects=False
            )
        except (httpx.TimeoutException, httpx.TransportError):
            return chain, None, None, None
        chain.append(url)
        if resp.is_redirect:
            location = resp.headers.get("location")
            if not location:
                return chain, None, resp.content, resp.status_code
            url = str(httpx.URL(url).join(location))
            continue
        final_host = urlparse(url).hostname
        return chain, final_host, resp.content, resp.status_code
    return chain, None, None, None


def _looks_parked(
    nameservers: list[str],
    body: Optional[bytes],
    title: Optional[str],
    heading: Optional[str],
) -> bool:
    for ns in nameservers:
        if any(marker in ns for marker in _PARKING_NAMESERVER_MARKERS):
            return True
    if body:
        lower = body.lower()
        if any(marker.encode() in lower for marker in _PARKING_PAGE_MARKERS):
            return True
    for text in (title, heading):
        if text and any(marker in text.lower() for marker in _PARKED_TITLE_MARKERS):
            return True
    return False


async def resolve_a(client: httpx.AsyncClient, resolver_url: str, domain: str) -> list[str]:
    """Public wrapper used by squatwatch.defend for the A-record fallback
    when sandbox URL forwarding is unavailable (F8)."""
    return await _doh_lookup(client, resolver_url, domain, "A")


async def classify(
    client: httpx.AsyncClient,
    resolver_url: str,
    domain: str,
    brand_registrable: str,
    cache: Optional[Cache] = None,
) -> ProbeInfo:
    """Classify one registered candidate: forwards-home / live-other /
    parked / mail-only / dark / unknown. Cached 24h per domain (F12) when
    a Cache is supplied — a re-probe within that window costs nothing.
    """
    cache_key = f"probe:{domain}"
    if cache is not None:
        cached = cache.get(cache_key)
        if cached is not None:
            return ProbeInfo(**cached)

    result = await _classify_uncached(client, resolver_url, domain, brand_registrable)

    if cache is not None:
        cache.set(cache_key, result.model_dump())
    return result


async def _classify_uncached(
    client: httpx.AsyncClient,
    resolver_url: str,
    domain: str,
    brand_registrable: str,
) -> ProbeInfo:
    sem = get_semaphore("probe", PROBE_CONCURRENCY)
    async with sem:
        a_records, mx_records, ns_records = await asyncio.gather(
            _doh_lookup(client, resolver_url, domain, "A"),
            _doh_lookup(client, resolver_url, domain, "MX"),
            _doh_lookup(client, resolver_url, domain, "NS"),
        )

        info = ProbeInfo(a=a_records, mx=mx_records)

        if not a_records and not mx_records:
            info.kind = ProbeKind.DARK
            return info

        if not a_records and mx_records:
            info.kind = ProbeKind.MAIL_ONLY
            return info

        chain, final_host, body, status = await _follow_chain(client, domain)
        info.chain = chain
        info.final_host = final_host

        if final_host is None and status is None and not chain:
            info.kind = ProbeKind.UNKNOWN
            return info

        homes = _registrable_and_www(brand_registrable)
        if final_host and final_host.lower() in homes:
            info.kind = ProbeKind.FORWARDS_HOME
            return info

        title = _extract_title(body) if body else None
        heading = _extract_first_heading(body) if body else None

        if _looks_parked(ns_records, body, title, heading):
            info.kind = ProbeKind.PARKED
            return info

        if status and 200 <= status < 300 and final_host:
            info.kind = ProbeKind.LIVE_OTHER
            info.title = title
            return info

        # `a_records` is guaranteed non-empty by this point (the two
        # early returns above are the only paths for an empty A list),
        # so this domain has *some* web-facing infrastructure even
        # though we couldn't cleanly classify it (redirect loop, non-2xx
        # final status, chain that didn't resolve within MAX_HOPS).
        # MUST NOT fall back to mail-only here: that claim ("no
        # website") would be false for a domain we know has an A
        # record — examiner_report.md Round 1 P1 caught exactly this
        # (8 of 9 "mail-only" cards in a live scan actually had live
        # sites). Honest answer is "we don't know," not "no website."
        info.kind = ProbeKind.UNKNOWN
        return info
